spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  application:
    name: academy


jwt:
  issuer: academy@academy.com
  secret_key: ${JWT_SECRET_KEY}
  expiration: ${ACCESS_TOKEN_EXPIRATION} #86400000
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION} #604800000


naver:
  service:
    url: ${NAVER_SERVICE_URL}
    secretKey: ${NAVER_SERVICE_SECRET_KEY}


cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
